### ISSUE TITLE
EZSArray中的如下代码实现并不是线程安全的。

### ISSUE THREAD

**Issue by youngsoft** [meituan/EasySequence#17]
- (void)removeLastObject {
    if (self.count >= 1) {
        [self removeObjectAtIndex:(self.count - 1)];
    }
}

- (void)removeFirstObject {
    if (self.count > 0){
        [self removeObjectAtIndex:0];
    }
}

**Comment by WilliamZang** [comment]
@youngsoft 感谢发现问题，这段代码中 `self.count` 和 `-self removeObjectAtIndex:` 本身是线程安全的。但是这样写的确有问题，由于取 count 和删除操作并没有原子操作，在多线程下会出现数据不一致的问题，我会提 PR 解决这个问题，到时候再关联并关闭这个 issue。
