### ISSUE TITLE
pod install error: Unable to find a specification for `EasyFoundation (~> 1.0.0-alpha)` depended upon by `EasyReact`

### ISSUE THREAD

**Issue by wangyingbo** [meituan/EasySequence#3]
<img width="576" alt="error" src="https://user-images.githubusercontent.com/12741589/42433677-f686a36c-8382-11e8-86fa-732d1dc3c7ef.png">

**Comment by ValiantCat** [comment]
please use `pod repo update master` update the podspeces repo.
